### ISSUE TITLE
Error on set/create a value in json object

### ISSUE THREAD

**Issue by Jonseed** [lucafoscili/comfyui-lf#109]
Got this error today when trying to create a second key-value in JSON.

```
!!! Exception during processing !!! Expected a dictionary inside the list, but got <class 'list'>
Traceback (most recent call last):
  File "D:\repos\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repos\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repos\ComfyUI\execution.py", line 163, in _map_node_over_list
    process_inputs(input_data_all, 0)
  File "D:\repos\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\repos\ComfyUI\custom_nodes\comfyui-lf\modules\nodes\json.py", line 270, in on_exec
    raise TypeError(f"Expected a dictionary inside the list, but got {type(json_obj)}")
TypeError: Expected a dictionary inside the list, but got <class 'list'>
```

My JSON is in this format:

```
{
  "Description": "This is the description.",
  "Title": "This is the title",
  "Subject": [
    "keyword1",
    "keyword2",
    "keyword3"
  ]
}
```

I set a key as "Author" and value as "Author's name." After creating this first key-value, the JSON looks like this. Is it putting the JSON inside a list? And did it set the Author's value in a list too?

```
[
  {
    "Description": "This is the description.",
    "Title": "This is the title",
    "Subject": [
      "keyword1",
      "keyword2",
      "keyword3"
    ],
    "Author": [
      "Author's name"
    ]
  }
]
```

Then I get the error on the second set/create node that tries to create another key-value.

**Comment by lucafoscili** [comment]
Hey, can you try out this branch?
I revamped the node, now it should behave correctly and also accept any type as value.

=> https://github.com/lucafoscili/comfyui-lf/tree/5-1-4

![workflow (1)](https://github.com/user-attachments/assets/0f6a0df3-f663-40a8-b12b-514e458fa43d)

**Comment by Jonseed** [comment]
Thanks! Branch 5-1-4 works great for me. Of course, I had to add some primitive nodes to input into value, but once I did that, I got valid JSON and no errors.

```
{
  "Description": "This is the description.",
  "Title": "This is the title",
  "Subject": [
    "keyword1",
    "keyword2",
    "keyword3"
  ],
  "Author": "Author's name",
  "Copyright": "My copyright"
}
```

**Comment by lucafoscili** [comment]
Yeah, it's kinda annoying having to define primitives but I think that trading off the embedded text field for the possibility to set any value is better.
Anyway, merged the branch into master - let me know if everything's ok!
